const data = {
  title: "홈투데이",
  screen_name: "TODAY",
  view_event_logging: {},
  logging: {
    SCREEN: "TODAY",
  },
  components: [
    {
      component_id: 128,
      type: {
        header: null,
        item_list: "TWO_COL_CARD_LIST",
        footer: null,
      },
      logging: {
        analytics: {
          LIST_ID: "today_recommend",
        },
        ably_only_log: {
          list_id: "today_recommend",
        },
      },
      entity: {
        header: null,
        item_list: [
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 52828654,
                name: "LITTLE 슬림핏 레이어드 롱 슬리브 5 COLORS",
                image: "https://d3ha2047wt6x28.cloudfront.net/NfJ61VZl-Dg/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2M5MDBkZTYzOTMxYmRjM2E0ZjUwYTJjYTk1YjU5NmQ2LmpwZw",
                market_sno: 56740,
                market_name: "프라임에이트",
                market_type: "캐주얼 브랜드",
                delivery_type: "standard",
                sell_count: 94,
                discount_rate: 34,
                first_page_rendering: {
                  goods_name: "LITTLE 슬림핏 레이어드 롱 슬리브 5 COLORS",
                  market_name: " 프라임에이트",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/Bp1Di_NFxZY/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwOTA5XzE3NTc0MDE4MDIwMzkzNzFtLmpwZw",
                  market_image: null,
                  discount_rate: 34,
                  original_price: 39800,
                  price: 25900,
                },
                is_new: false,
                price: 25900,
                like: {
                  goods_sno: 52828654,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 23,
                  },
                },
                ad: {
                  list_id: "recommend",
                  campaign_id: "494518",
                  parameters:
                    '{"generated_at": "2025-09-19 16:51:37", "market_sno": 56740, "ad_market_sno": 27433, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QZcANM8jfcTWkjfhsJfebmPUJk8iyqcg89oD5vlDwh+W5zHEVQ4UmfFfZRXBnhqMncwswGNWoVaZjDYaZO6LRc3gPSBguxobO2GlzyVQz4fIhdPN1poUn9ZP2/s4PpJAcNp/x/dRsFae5wZvAzbzqVXzAtFy3UsR16qvApS3uhbI2W1Jts1583N8ow3QTPG1IvGEW+A3lVwSUwfLwTvg2KXSQoqApPdn/qcmnudYJJ2HCc1EWU9fRnb4/qhl+xY2Fyi7GPBeye8mAfvxiT5TtnBIEzwlO/A8dv0/xu/NLw7Qw==", "list_index": 23}',
                  goods_sno: 52828654,
                },
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/52828654/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "긴소매티셔츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 23,
                  pool: "ad",
                  goods_sno: 52828654,
                  ad: {
                    list_id: "recommend",
                    campaign_id: "494518",
                    parameters:
                      '{"generated_at": "2025-09-19 16:51:37", "market_sno": 56740, "ad_market_sno": 27433, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QZcANM8jfcTWkjfhsJfebmPUJk8iyqcg89oD5vlDwh+W5zHEVQ4UmfFfZRXBnhqMncwswGNWoVaZjDYaZO6LRc3gPSBguxobO2GlzyVQz4fIhdPN1poUn9ZP2/s4PpJAcNp/x/dRsFae5wZvAzbzqVXzAtFy3UsR16qvApS3uhbI2W1Jts1583N8ow3QTPG1IvGEW+A3lVwSUwfLwTvg2KXSQoqApPdn/qcmnudYJJ2HCc1EWU9fRnb4/qhl+xY2Fyi7GPBeye8mAfvxiT5TtnBIEzwlO/A8dv0/xu/NLw7Qw==", "list_index": 23}',
                    goods_sno: 52828654,
                  },
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "52828654",
                  GOODS_NAME: "LITTLE 슬림핏 레이어드 롱 슬리브 5 COLORS",
                  MARKET_TYPE: "캐주얼 브랜드",
                  MARKET_SNO: "56740",
                  MARKET_NAME: "프라임에이트",
                  CATEGORY_SNO: "498",
                  CATEGORY_NAME: "긴소매티셔츠",
                  STANDARD_CATEGORY_SNO: "23",
                  STANDARD_CATEGORY_NAME: "긴소매티셔츠",
                  DISCOUNT_RATE: 34,
                  SALES_PRICE: 25900,
                  SALES_PRICE_RANGE: "25,001~30,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "1",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "12",
                  REVIEW_COUNT: 1,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 100,
                  LIKES_COUNT: 528,
                  LIKES_COUNT_RANGE: "501~550",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 23,
                  BRAND_SNO: 15205,
                  BRAND_NAME: "프라임에이트",
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/NfJ61VZl-Dg/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2M5MDBkZTYzOTMxYmRjM2E0ZjUwYTJjYTk1YjU5NmQ2LmpwZw",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "LITTLE 슬림핏 레이어드 롱 슬리브 5 COLORS",
                  price: "25,900",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "34%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "<font color='#6093FC'>브랜드</font> 프라임에이트",
                  nudging_text: "94개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 38430344,
                name: "[💘ONLY ABLY][컬러추가]MRT 카모 래글런 후드티",
                image: "https://d3ha2047wt6x28.cloudfront.net/_N-tQtaSUkE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2UzY2ZlZDcwMGE1OTZlMWVmMTJhNDBmNGQ3MzRmOTdmLmdpZg",
                market_sno: 29178,
                market_name: "벤힛",
                market_type: "캐주얼 브랜드",
                delivery_type: "standard",
                sell_count: 8020,
                discount_rate: 46,
                first_page_rendering: {
                  goods_name: "[💘ONLY ABLY][컬러추가]MRT 카모 래글런 후드티",
                  market_name: " 벤힛",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/SsSRKVUMY54/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwOTAzXzE3NTY4ODgwNzM3MTExMDRtLmpwZw",
                  market_image: null,
                  discount_rate: 46,
                  original_price: 72000,
                  price: 38320,
                },
                is_new: false,
                price: 38320,
                like: {
                  goods_sno: 38430344,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 24,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/38430344/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "후드",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 24,
                  pool: "basic_reco",
                  goods_sno: 38430344,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "38430344",
                  GOODS_NAME: "[💘ONLY ABLY][컬러추가]MRT 카모 래글런 후드티",
                  MARKET_TYPE: "캐주얼 브랜드",
                  MARKET_SNO: "29178",
                  MARKET_NAME: "벤힛",
                  CATEGORY_SNO: "500",
                  CATEGORY_NAME: "후드",
                  STANDARD_CATEGORY_SNO: "26",
                  STANDARD_CATEGORY_NAME: "후드",
                  DISCOUNT_RATE: 46,
                  SALES_PRICE: 38320,
                  SALES_PRICE_RANGE: "35,001~40,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "12",
                  REVIEW_COUNT: 1041,
                  REVIEW_COUNT_RANGE: "1,001~1,050",
                  REVIEW_RATING: 98,
                  LIKES_COUNT: 30169,
                  LIKES_COUNT_RANGE: "30,151~30,200",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: true,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "ONLY_ABLY"],
                      ["image_url", "https://d3ha2047wt6x28.cloudfront.net/lk7oDFuANYQ/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYWJseV9vbmx5LnBuZw"],
                      ["image_width", 58],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 24,
                  BRAND_SNO: 748,
                  BRAND_NAME: "벤힛",
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS", "PRICE_DESCRIPTION"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/_N-tQtaSUkE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2UzY2ZlZDcwMGE1OTZlMWVmMTJhNDBmNGQ3MzRmOTdmLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[💘ONLY ABLY][컬러추가]MRT 카모 래글런 후드티",
                  price: "38,320",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "46%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [
                    {
                      type: "ONLY_ABLY",
                      image_url: "https://d3ha2047wt6x28.cloudfront.net/lk7oDFuANYQ/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYWJseV9vbmx5LnBuZw",
                      image_width: 58,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "<font color='#6093FC'>브랜드</font> 벤힛",
                  nudging_text: "8,020개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: {
                    icon_url: "https://img.a-bly.com/data/goods/badge/icon_coupon_filled.png",
                    text: "쿠폰적용가",
                  },
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 49191569,
                name: "FB 그래피티 로고 후드티",
                image: "https://d3ha2047wt6x28.cloudfront.net/koezxRHWPkg/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2I4MTdlODdhMTEzNzA0OGI1MmZhNDdkMmMwODQxZmE1LmdpZg",
                market_sno: 12629,
                market_name: "어나더아카이브",
                market_type: "캐주얼 브랜드",
                delivery_type: "standard",
                sell_count: 2024,
                discount_rate: 36,
                first_page_rendering: {
                  goods_name: "FB 그래피티 로고 후드티",
                  market_name: " 어나더아카이브",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/1bYh2UGKTLg/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwODIxXzE3NTU3ODEzNzc3ODQxODFtLmpwZw",
                  market_image: null,
                  discount_rate: 36,
                  original_price: 49800,
                  price: 31800,
                },
                is_new: false,
                price: 31800,
                like: {
                  goods_sno: 49191569,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 25,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/49191569/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "후드",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 25,
                  pool: "basic_reco",
                  goods_sno: 49191569,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "49191569",
                  GOODS_NAME: "FB 그래피티 로고 후드티",
                  MARKET_TYPE: "캐주얼 브랜드",
                  MARKET_SNO: "12629",
                  MARKET_NAME: "어나더아카이브",
                  CATEGORY_SNO: "500",
                  CATEGORY_NAME: "후드",
                  STANDARD_CATEGORY_SNO: "26",
                  STANDARD_CATEGORY_NAME: "후드",
                  DISCOUNT_RATE: 36,
                  SALES_PRICE: 31800,
                  SALES_PRICE_RANGE: "30,001~35,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "12",
                  REVIEW_COUNT: 125,
                  REVIEW_COUNT_RANGE: "101~150",
                  REVIEW_RATING: 96,
                  LIKES_COUNT: 4794,
                  LIKES_COUNT_RANGE: "4,751~4,800",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: true,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "ONLY_ABLY"],
                      ["image_url", "https://d3ha2047wt6x28.cloudfront.net/lk7oDFuANYQ/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYWJseV9vbmx5LnBuZw"],
                      ["image_width", 58],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 25,
                  BRAND_SNO: 1074,
                  BRAND_NAME: "어나더아카이브",
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/koezxRHWPkg/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2I4MTdlODdhMTEzNzA0OGI1MmZhNDdkMmMwODQxZmE1LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "FB 그래피티 로고 후드티",
                  price: "31,800",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "36%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [
                    {
                      type: "ONLY_ABLY",
                      image_url: "https://d3ha2047wt6x28.cloudfront.net/lk7oDFuANYQ/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYWJseV9vbmx5LnBuZw",
                      image_width: 58,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "<font color='#6093FC'>브랜드</font> 어나더아카이브",
                  nudging_text: "2,024개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 47604589,
                name: "밀란 시그니처 로고 후드 바람막이 윈드브레이커",
                image: "https://d3ha2047wt6x28.cloudfront.net/Fk3t-KuwDLs/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2QwZmFhNTkwZGVkMzRlMWUyYTllMjQ0MWIzNTExYjIxLmdpZg",
                market_sno: 64043,
                market_name: "무센트",
                market_type: "스트릿 브랜드",
                delivery_type: "standard",
                sell_count: 1794,
                discount_rate: 33,
                first_page_rendering: {
                  goods_name: "밀란 시그니처 로고 후드 바람막이 윈드브레이커",
                  market_name: " 무센트",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/CcaumA3rTWA/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwODIwXzE3NTU2NjIwNzM2MTg2OTNtLnBuZw",
                  market_image: null,
                  discount_rate: 33,
                  original_price: 94100,
                  price: 62610,
                },
                is_new: false,
                price: 62610,
                like: {
                  goods_sno: 47604589,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 26,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/47604589/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "바람막이",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 26,
                  pool: "basic_reco",
                  goods_sno: 47604589,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "47604589",
                  GOODS_NAME: "밀란 시그니처 로고 후드 바람막이 윈드브레이커",
                  MARKET_TYPE: "스트릿 브랜드",
                  MARKET_SNO: "64043",
                  MARKET_NAME: "무센트",
                  CATEGORY_SNO: "497",
                  CATEGORY_NAME: "바람막이",
                  STANDARD_CATEGORY_SNO: "11",
                  STANDARD_CATEGORY_NAME: "바람막이",
                  DISCOUNT_RATE: 33,
                  SALES_PRICE: 62610,
                  SALES_PRICE_RANGE: "60,001~65,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "11",
                  REVIEW_COUNT: 46,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 93,
                  LIKES_COUNT: 7840,
                  LIKES_COUNT_RANGE: "7,801~7,850",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 26,
                  BRAND_SNO: 14035,
                  BRAND_NAME: "무센트",
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/Fk3t-KuwDLs/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2QwZmFhNTkwZGVkMzRlMWUyYTllMjQ0MWIzNTExYjIxLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "밀란 시그니처 로고 후드 바람막이 윈드브레이커",
                  price: "62,610",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "33%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "<font color='#6093FC'>브랜드</font> 무센트",
                  nudging_text: "1,794개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 28784208,
                name: "[기모/NO기모] SEVEN 오버핏 후드 티셔츠 9 COLORS",
                image: "https://d3ha2047wt6x28.cloudfront.net/lOrTUHpoUqY/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIyZGM0NDAyMzQzOTI0NDNhZTIwOTFkYmM2YzU5MWE4LmpwZw",
                market_sno: 56740,
                market_name: "프라임에이트",
                market_type: "캐주얼 브랜드",
                delivery_type: "standard",
                sell_count: 5087,
                discount_rate: 23,
                first_page_rendering: {
                  goods_name: "[기모/NO기모] SEVEN 오버핏 후드 티셔츠 9 COLORS",
                  market_name: " 프라임에이트",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/l3ypZqV7mWw/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjQwOTI3XzE3Mjc0MTQ0NTAwNTE3MjZtLmpwZw",
                  market_image: null,
                  discount_rate: 23,
                  original_price: 52800,
                  price: 40600,
                },
                is_new: false,
                price: 40600,
                like: {
                  goods_sno: 28784208,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 27,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/28784208/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "후드",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 27,
                  pool: "basic_reco",
                  goods_sno: 28784208,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "28784208",
                  GOODS_NAME: "[기모/NO기모] SEVEN 오버핏 후드 티셔츠 9 COLORS",
                  MARKET_TYPE: "캐주얼 브랜드",
                  MARKET_SNO: "56740",
                  MARKET_NAME: "프라임에이트",
                  CATEGORY_SNO: "500",
                  CATEGORY_NAME: "후드",
                  STANDARD_CATEGORY_SNO: "26",
                  STANDARD_CATEGORY_NAME: "후드",
                  DISCOUNT_RATE: 23,
                  SALES_PRICE: 40600,
                  SALES_PRICE_RANGE: "40,001~45,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "12",
                  REVIEW_COUNT: 704,
                  REVIEW_COUNT_RANGE: "701~750",
                  REVIEW_RATING: 97,
                  LIKES_COUNT: 19323,
                  LIKES_COUNT_RANGE: "19,301~19,350",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 27,
                  BRAND_SNO: 15205,
                  BRAND_NAME: "프라임에이트",
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/lOrTUHpoUqY/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIyZGM0NDAyMzQzOTI0NDNhZTIwOTFkYmM2YzU5MWE4LmpwZw",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[기모/NO기모] SEVEN 오버핏 후드 티셔츠 9 COLORS",
                  price: "40,600",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "23%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "<font color='#6093FC'>브랜드</font> 프라임에이트",
                  nudging_text: "5,087개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 52606442,
                name: "[MADE💖][차르르~/쫀쫀골지] 극강의 여리핏, 로헨느 버튼 라운드 긴팔티",
                image: "https://d3ha2047wt6x28.cloudfront.net/-1rD-I7BVSE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIyNmI0MjM3ZDc4NGViNzIzZGZhMDhkNzc1NmRkZmI4LmdpZg",
                market_sno: 34446,
                market_name: "크림슈가",
                market_type: "쇼핑몰",
                delivery_type: "standard",
                sell_count: 1208,
                discount_rate: 24,
                first_page_rendering: {
                  goods_name: "[MADE💖][차르르~/쫀쫀골지] 극강의 여리핏, 로헨느 버튼 라운드 긴팔티",
                  market_name: "크림슈가",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/xx6OVfxVdsc/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwOTA3XzE3NTcyMDE0NzIyNzYzMDNtLmpwZw",
                  market_image: null,
                  discount_rate: 24,
                  original_price: 25000,
                  price: 18990,
                },
                is_new: false,
                price: 18990,
                like: {
                  goods_sno: 52606442,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 28,
                  },
                },
                ad: {
                  list_id: "recommend",
                  campaign_id: "492232",
                  parameters:
                    '{"generated_at": "2025-09-19 16:51:37", "market_sno": 34446, "ad_market_sno": 11295, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QaFGKKpm/e0qTh+2IOqlS8nMtLAGcJzx8RCJe1d13TDxDyS74+W2kYMaUIyudhFpRYwswGNWoVaZjDYaZO6LRc3gnArBB3Ot2xGIpZvFWkQwl43ORWlgmVyUmZq/tUc96hp/x/dRsFae5wZvAzbzqVXzAtFy3UsR16qvApS3uhbI83gXdBnQ2OWR2m+xTDxTRzGEW+A3lVwSUwfLwTvg2KXjLFcHnTntOXqWixtNcEmv5xcvFdk1yRC57BqyvgeGb/3WoARY2gHCSlwj7LAmQ2dQvOXgPKu+LG77nYaTAzPKA==", "list_index": 28}',
                  goods_sno: 52606442,
                },
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/52606442/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "긴소매티셔츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 28,
                  pool: "ad",
                  goods_sno: 52606442,
                  ad: {
                    list_id: "recommend",
                    campaign_id: "492232",
                    parameters:
                      '{"generated_at": "2025-09-19 16:51:37", "market_sno": 34446, "ad_market_sno": 11295, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QaFGKKpm/e0qTh+2IOqlS8nMtLAGcJzx8RCJe1d13TDxDyS74+W2kYMaUIyudhFpRYwswGNWoVaZjDYaZO6LRc3gnArBB3Ot2xGIpZvFWkQwl43ORWlgmVyUmZq/tUc96hp/x/dRsFae5wZvAzbzqVXzAtFy3UsR16qvApS3uhbI83gXdBnQ2OWR2m+xTDxTRzGEW+A3lVwSUwfLwTvg2KXjLFcHnTntOXqWixtNcEmv5xcvFdk1yRC57BqyvgeGb/3WoARY2gHCSlwj7LAmQ2dQvOXgPKu+LG77nYaTAzPKA==", "list_index": 28}',
                    goods_sno: 52606442,
                  },
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "52606442",
                  GOODS_NAME: "[MADE💖][차르르~/쫀쫀골지] 극강의 여리핏, 로헨느 버튼 라운드 긴팔티",
                  MARKET_TYPE: "쇼핑몰",
                  MARKET_SNO: "34446",
                  MARKET_NAME: "크림슈가",
                  CATEGORY_SNO: "498",
                  CATEGORY_NAME: "긴소매티셔츠",
                  STANDARD_CATEGORY_SNO: "23",
                  STANDARD_CATEGORY_NAME: "긴소매티셔츠",
                  DISCOUNT_RATE: 24,
                  SALES_PRICE: 18990,
                  SALES_PRICE_RANGE: "15,001~20,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "1",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "8",
                  REVIEW_COUNT: 3,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 100,
                  LIKES_COUNT: 5054,
                  LIKES_COUNT_RANGE: "5,051~5,100",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 28,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/-1rD-I7BVSE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIyNmI0MjM3ZDc4NGViNzIzZGZhMDhkNzc1NmRkZmI4LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[MADE💖][차르르~/쫀쫀골지] 극강의 여리핏, 로헨느 버튼 라운드 긴팔티",
                  price: "18,990",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "24%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "크림슈가",
                  nudging_text: "1,208개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 52207438,
                name: "[기모/NO기모] SONG 오버핏 후드 티셔츠 8 COLORS",
                image: "https://d3ha2047wt6x28.cloudfront.net/gsu7pIGBqhE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzlkYWVlNjRiMmI3MGFlNGUyODQzY2E2ZDViYTdmZTQyLmpwZw",
                market_sno: 56740,
                market_name: "프라임에이트",
                market_type: "캐주얼 브랜드",
                delivery_type: "standard",
                sell_count: 1104,
                discount_rate: 23,
                first_page_rendering: {
                  goods_name: "[기모/NO기모] SONG 오버핏 후드 티셔츠 8 COLORS",
                  market_name: " 프라임에이트",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/FbkJHngOgbE/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwOTAxXzE3NTY2ODkyNDAyNjE5OTVtLmpwZw",
                  market_image: null,
                  discount_rate: 23,
                  original_price: 52800,
                  price: 40600,
                },
                is_new: false,
                price: 40600,
                like: {
                  goods_sno: 52207438,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 29,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/52207438/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "후드",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 29,
                  pool: "basic_reco",
                  goods_sno: 52207438,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "52207438",
                  GOODS_NAME: "[기모/NO기모] SONG 오버핏 후드 티셔츠 8 COLORS",
                  MARKET_TYPE: "캐주얼 브랜드",
                  MARKET_SNO: "56740",
                  MARKET_NAME: "프라임에이트",
                  CATEGORY_SNO: "500",
                  CATEGORY_NAME: "후드",
                  STANDARD_CATEGORY_SNO: "26",
                  STANDARD_CATEGORY_NAME: "후드",
                  DISCOUNT_RATE: 23,
                  SALES_PRICE: 40600,
                  SALES_PRICE_RANGE: "40,001~45,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "12",
                  REVIEW_COUNT: 23,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 100,
                  LIKES_COUNT: 6575,
                  LIKES_COUNT_RANGE: "6,551~6,600",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 29,
                  BRAND_SNO: 15205,
                  BRAND_NAME: "프라임에이트",
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/gsu7pIGBqhE/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzlkYWVlNjRiMmI3MGFlNGUyODQzY2E2ZDViYTdmZTQyLmpwZw",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[기모/NO기모] SONG 오버핏 후드 티셔츠 8 COLORS",
                  price: "40,600",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "23%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "<font color='#6093FC'>브랜드</font> 프라임에이트",
                  nudging_text: "1,104개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 52177024,
                name: "[가을신상🍂/MADE] 에디리 스트라이프 박스 긴팔티 [자체제작 제작상품 긴팔티셔츠 줄무늬 패턴 가을긴팔 데일리 꾸안꾸]",
                image: "https://d3ha2047wt6x28.cloudfront.net/1uZdIf-q_QA/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzMyYTU1ZDc3NjU1YjJmNjFlYzZiYjMxZTA0ZTVlMzMwLmdpZg",
                market_sno: 13045,
                market_name: "블랙업",
                market_type: "쇼핑몰",
                delivery_type: "standard",
                sell_count: 170,
                discount_rate: 5,
                first_page_rendering: {
                  goods_name: "[가을신상🍂/MADE] 에디리 스트라이프 박스 긴팔티 [자체제작 제작상품 긴팔티셔츠 줄무늬 패턴 가을긴팔 데일리 꾸안꾸]",
                  market_name: "블랙업",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/KDRK9AszkGU/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwODI5XzE3NTY0MzQ4NTYyNjEyNzBtLmpwZw",
                  market_image: null,
                  discount_rate: 5,
                  original_price: 28000,
                  price: 26600,
                },
                is_new: false,
                price: 26600,
                like: {
                  goods_sno: 52177024,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 30,
                  },
                },
                ad: {
                  list_id: "recommend",
                  campaign_id: "471099",
                  parameters:
                    '{"generated_at": "2025-09-19 16:51:37", "market_sno": 13045, "ad_market_sno": 39885, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QaVjXySOnIAbKQutZox3l92Expc5Ft0M9x/oGV1XSOu92PIePsXXPq//2c8yVjudP0wswGNWoVaZjDYaZO6LRc3j2eZyCzrrsR6eWwUd1rPvNunKagJJPUa99mWi4lPc5Np/x/dRsFae5wZvAzbzqVXzAtFy3UsR16qvApS3uhbI8rvMcMiKJaa9TFPwEq57qgiINyCH/Uc/YLWBbJhGP+wygLkKB3/gPlWeiOLmoK/d1BJw880iGvAKke6Y09rns1UAYrl7d8nBZg1SitZk+RTA/8imSgMgfXXLgN5/Go0Lw==", "list_index": 30}',
                  goods_sno: 52177024,
                },
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/52177024/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "긴소매티셔츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 30,
                  pool: "ad",
                  goods_sno: 52177024,
                  ad: {
                    list_id: "recommend",
                    campaign_id: "471099",
                    parameters:
                      '{"generated_at": "2025-09-19 16:51:37", "market_sno": 13045, "ad_market_sno": 39885, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2QaVjXySOnIAbKQutZox3l92Expc5Ft0M9x/oGV1XSOu92PIePsXXPq//2c8yVjudP0wswGNWoVaZjDYaZO6LRc3j2eZyCzrrsR6eWwUd1rPvNunKagJJPUa99mWi4lPc5Np/x/dRsFae5wZvAzbzqVXzAtFy3UsR16qvApS3uhbI8rvMcMiKJaa9TFPwEq57qgiINyCH/Uc/YLWBbJhGP+wygLkKB3/gPlWeiOLmoK/d1BJw880iGvAKke6Y09rns1UAYrl7d8nBZg1SitZk+RTA/8imSgMgfXXLgN5/Go0Lw==", "list_index": 30}',
                    goods_sno: 52177024,
                  },
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "52177024",
                  GOODS_NAME: "[가을신상🍂/MADE] 에디리 스트라이프 박스 긴팔티 [자체제작 제작상품 긴팔티셔츠 줄무늬 패턴 가을긴팔 데일리 꾸안꾸]",
                  MARKET_TYPE: "쇼핑몰",
                  MARKET_SNO: "13045",
                  MARKET_NAME: "블랙업",
                  CATEGORY_SNO: "498",
                  CATEGORY_NAME: "긴소매티셔츠",
                  STANDARD_CATEGORY_SNO: "23",
                  STANDARD_CATEGORY_NAME: "긴소매티셔츠",
                  DISCOUNT_RATE: 5,
                  SALES_PRICE: 26600,
                  SALES_PRICE_RANGE: "25,001~30,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "1",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "8",
                  REVIEW_COUNT: 7,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 100,
                  LIKES_COUNT: 422,
                  LIKES_COUNT_RANGE: "401~450",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 30,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/1uZdIf-q_QA/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzMyYTU1ZDc3NjU1YjJmNjFlYzZiYjMxZTA0ZTVlMzMwLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[가을신상🍂/MADE] 에디리 스트라이프 박스 긴팔티 [자체제작 제작상품 긴팔티셔츠 줄무늬 패턴 가을긴팔 데일리 꾸안꾸]",
                  price: "26,600",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "5%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "블랙업",
                  nudging_text: "170개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 40356072,
                name: "[500장판매/unisex] 다잉 핑거홀 와플 티셔츠 -4C",
                image: "https://d3ha2047wt6x28.cloudfront.net/vyhFeUSgcu0/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzRlZWU0NWY1MGQzOGM5NzRlMjRiYWE4YWI4NTI0YzBhLmdpZg",
                market_sno: 73000,
                market_name: "원아브",
                market_type: "셀럽",
                delivery_type: "today",
                sell_count: 590,
                discount_rate: 12,
                first_page_rendering: {
                  goods_name: "[500장판매/unisex] 다잉 핑거홀 와플 티셔츠 -4C",
                  market_name: "원아브",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/K1aeQ8qBlI8/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwMjE0XzE3Mzk1MjU1Nzc3Nzk1MDltLmpwZw",
                  market_image: null,
                  discount_rate: 12,
                  original_price: 41000,
                  price: 36080,
                },
                is_new: false,
                price: 36080,
                like: {
                  goods_sno: 40356072,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 31,
                  },
                },
                ad: {
                  list_id: "recommend",
                  campaign_id: "493547",
                  parameters:
                    '{"generated_at": "2025-09-19 16:51:37", "market_sno": 73000, "ad_market_sno": 42017, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2Qae0qAKcMyI1OaHh3tEJj/xyGxsS493a62dZO/KrzCjDtmaRV20RacMArsNkgTZuStH6z5+0AY0jz90CZeN51VZ64jsHHbw/IYpF8s/FydpYlZbAn4MbE3faPaSnDw+mdJwMaJXFmAUV7XeUCJThJQUbgRYcCZguoIlr4RIr+DNgSUEUbmQnwwKNSDzQR+4ZmsiINyCH/Uc/YLWBbJhGP+wHf/tGhRaHH8SKuNz5drUV0KEeXSKVqsZ30n5VWrBH761P9cW9R5cpcUbrDpHyBaKB9GxtsCCo9tzT8M736gtsg==", "list_index": 31}',
                  goods_sno: 40356072,
                },
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/40356072/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "긴소매티셔츠",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 31,
                  pool: "ad",
                  goods_sno: 40356072,
                  ad: {
                    list_id: "recommend",
                    campaign_id: "493547",
                    parameters:
                      '{"generated_at": "2025-09-19 16:51:37", "market_sno": 73000, "ad_market_sno": 42017, "pool": "reco_in", "ei": "gUVx+3QMjXwOPJYv7+VqjM2W6RpakYsjPWs/nNZs2Qae0qAKcMyI1OaHh3tEJj/xyGxsS493a62dZO/KrzCjDtmaRV20RacMArsNkgTZuStH6z5+0AY0jz90CZeN51VZ64jsHHbw/IYpF8s/FydpYlZbAn4MbE3faPaSnDw+mdJwMaJXFmAUV7XeUCJThJQUbgRYcCZguoIlr4RIr+DNgSUEUbmQnwwKNSDzQR+4ZmsiINyCH/Uc/YLWBbJhGP+wHf/tGhRaHH8SKuNz5drUV0KEeXSKVqsZ30n5VWrBH761P9cW9R5cpcUbrDpHyBaKB9GxtsCCo9tzT8M736gtsg==", "list_index": 31}',
                    goods_sno: 40356072,
                  },
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "40356072",
                  GOODS_NAME: "[500장판매/unisex] 다잉 핑거홀 와플 티셔츠 -4C",
                  MARKET_TYPE: "셀럽",
                  MARKET_SNO: "73000",
                  MARKET_NAME: "원아브",
                  CATEGORY_SNO: "498",
                  CATEGORY_NAME: "긴소매티셔츠",
                  STANDARD_CATEGORY_SNO: "23",
                  STANDARD_CATEGORY_NAME: "긴소매티셔츠",
                  DISCOUNT_RATE: 12,
                  SALES_PRICE: 36080,
                  SALES_PRICE_RANGE: "35,001~40,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "today",
                  IS_AD: "1",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "7",
                  REVIEW_COUNT: 31,
                  REVIEW_COUNT_RANGE: "1~50",
                  REVIEW_RATING: 96,
                  LIKES_COUNT: 3897,
                  LIKES_COUNT_RANGE: "3,851~3,900",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: false,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "TODAY_DELIVERY"],
                      ["image_url", "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n"],
                      ["image_width", 46],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 31,
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/vyhFeUSgcu0/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzRlZWU0NWY1MGQzOGM5NzRlMjRiYWE4YWI4NTI0YzBhLmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[500장판매/unisex] 다잉 핑거홀 와플 티셔츠 -4C",
                  price: "36,080",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "12%",
                  closed_reason: null,
                  image_badge: "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                  image_badge_width: 46,
                  image_badge_height: 18,
                  image_badge_list: [
                    {
                      type: "TODAY_DELIVERY",
                      image_url: "https://d3ha2047wt6x28.cloudfront.net/ed29a9GcSUo/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYmFkZ2VfdG9kYXlfZGVsaXZlcnkucG5n",
                      image_width: 46,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "원아브",
                  nudging_text: "590개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
          {
            type: "GOODS_CARD",
            item_entity: {
              item: {
                sno: 23413380,
                name: "[25FW컬러 리뉴얼]그래피티 로고 후드티",
                image: "https://d3ha2047wt6x28.cloudfront.net/wPCqk3DLHzw/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2VlZDU5ZGU2YzliNDQ3ZTMxM2E4MjI1YjBmZjkxNzA1LmdpZg",
                market_sno: 12629,
                market_name: "어나더아카이브",
                market_type: "캐주얼 브랜드",
                delivery_type: "standard",
                sell_count: 45557,
                discount_rate: 34,
                first_page_rendering: {
                  goods_name: "[25FW컬러 리뉴얼]그래피티 로고 후드티",
                  market_name: " 어나더아카이브",
                  cover_image: "https://d3ha2047wt6x28.cloudfront.net/XMzg-R-fr84/pr:GOODS_DETAIL/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzLzIwMjUwODEyXzE3NTQ5NjQxODYxNzM0MzZtLmpwZw",
                  market_image: null,
                  discount_rate: 34,
                  original_price: 49800,
                  price: 32800,
                },
                is_new: false,
                price: 32800,
                like: {
                  goods_sno: 23413380,
                  is_liked: false,
                  folder_sno: null,
                  referrer: {
                    list_id: "today_recommend",
                    list_index: 32,
                  },
                },
                ad: null,
                on_return: {
                  type: "INJECT",
                  data: {
                    url: "goods/23413380/recommend_related_goods_by_click_for_today/?from=TODAY",
                  },
                },
                category_name: "후드",
                feedback_type: "contain_icon",
                remote_deeplink: null,
              },
              logging: {
                ably_only_log: {
                  schema_name: "Goods",
                  list_id: "today_recommend",
                  list_index: 32,
                  pool: "basic_reco",
                  goods_sno: 23413380,
                },
                analytics: {
                  IS_COPY_TARGET_GOODS: false,
                  GOODS_SNO: "23413380",
                  GOODS_NAME: "[25FW컬러 리뉴얼]그래피티 로고 후드티",
                  MARKET_TYPE: "캐주얼 브랜드",
                  MARKET_SNO: "12629",
                  MARKET_NAME: "어나더아카이브",
                  CATEGORY_SNO: "500",
                  CATEGORY_NAME: "후드",
                  STANDARD_CATEGORY_SNO: "26",
                  STANDARD_CATEGORY_NAME: "후드",
                  DISCOUNT_RATE: 34,
                  SALES_PRICE: 32800,
                  SALES_PRICE_RANGE: "30,001~35,000",
                  IS_NEW: "0",
                  DELIVERY_TYPE: "standard",
                  IS_AD: "0",
                  LIST_PARAMS: null,
                  MARKET_TYPE_SNO: "12",
                  REVIEW_COUNT: 10155,
                  REVIEW_COUNT_RANGE: "10,151~10,200",
                  REVIEW_RATING: 98,
                  LIKES_COUNT: 74552,
                  LIKES_COUNT_RANGE: "74,551~74,600",
                  PROMOTION_TAG: ["FIRST_PURCHASE_BENEFIT"],
                  HAS_AWARD: false,
                  IS_ONLY_ABLY: true,
                  IMAGE_BADGE_LIST: [
                    [
                      ["type", "ONLY_ABLY"],
                      ["image_url", "https://d3ha2047wt6x28.cloudfront.net/lk7oDFuANYQ/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYWJseV9vbmx5LnBuZw"],
                      ["image_width", 58],
                      ["image_height", 18],
                    ],
                  ],
                  LIST_ID: "today_recommend",
                  LIST_INDEX: 32,
                  BRAND_SNO: 1074,
                  BRAND_NAME: "어나더아카이브",
                },
              },
              render: {
                contents: ["PRICE", "NAME", "STORE", "NUDGING", "CHIPS"],
                size: "MEDIUM",
                data: {
                  image: {
                    url: "https://d3ha2047wt6x28.cloudfront.net/wPCqk3DLHzw/pr:NEW_GOODS_THUMB_WEBP/czM6Ly9hYmx5LWltYWdlLWxlZ2FjeS9kYXRhL2dvb2RzL2VlZDU5ZGU2YzliNDQ3ZTMxM2E4MjI1YjBmZjkxNzA1LmdpZg",
                    use_animation: true,
                    ratio: 1.2,
                  },
                  name: "[25FW컬러 리뉴얼]그래피티 로고 후드티",
                  price: "32,800",
                  has_ad_badge: false,
                  name_lines: 1,
                  discount_rate: "34%",
                  closed_reason: null,
                  image_badge: null,
                  image_badge_width: null,
                  image_badge_height: null,
                  image_badge_list: [
                    {
                      type: "ONLY_ABLY",
                      image_url: "https://d3ha2047wt6x28.cloudfront.net/lk7oDFuANYQ/pr:CONVERT_TO_WEBP/czM6Ly9pbWcuYS1ibHkuY29tL2RhdGEvZ29vZHMvYmFkZ2UvYWJseV9vbmx5LnBuZw",
                      image_width: 58,
                      image_height: 18,
                    },
                  ],
                  chips: [
                    {
                      meta: {
                        text_style: "subtitle6",
                        text_color: "#FF5160",
                        bg_color: "#FFEFF2",
                        border_color: "#FFEFF2",
                        border_width: 1,
                        rounded_corner_radius: 2,
                      },
                      name: "첫구매 혜택",
                      type: "DITTO_TEXT",
                    },
                  ],
                  store_text: "<font color='#6093FC'>브랜드</font> 어나더아카이브",
                  nudging_text: "45,557개 구매중",
                  ranking: null,
                  actions: ["LIKE"],
                  discount_end_text: null,
                  top_nudging_text: null,
                  price_description: null,
                  today_delivery_order_deadline_time: null,
                },
              },
            },
          },
        ],
        footer: null,
      },
    },
  ],
  next_token: "eyJsaSI6IDQsICJuIjogImV5SnNZWE4wWDJsdVpHVjRJam9nTXpOOSJ9",
  view_event_channels: ["firebase", "amplitude", "ablylog", "facebook", "appsflyer"],
};

// 옷 이름이랑 브랜드 마켓 이름, 판매된 수
// const quiz1 = data.components.map((v, i) => v.entity.item_list.map((v, i) => ({ name: v.item_entity.item.name, brandName: v.item_entity.item.market_name, sellCount: v.item_entity.item.sell_count })));

const quiz1 = data.components
  .map((v, i) => v.entity.item_list)
  .flat()
  .map((v, i) => ({ name: v.item_entity.item.name, brandName: v.item_entity.item.market_name, sellCount: v.item_entity.item.sell_count }));

console.log(quiz1);
